name: Release Charts
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: automation
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: failure()
        with:
          type: ${{ job.status }} 
          job_name: 'Helmchart Release Status: '
          url: ${{ secrets.RC_WEBHOOK }}
          channel: '#dbp-dev-monitoring'
          username: Helmchart Release Failure Notificator
